Use elif instead of nested else.

diff --git a/bin/carton b/bin/carton
--- a/bin/carton
+++ b/bin/carton
@@ -11,21 +11,17 @@ if [[ $# -eq 0 ]]; then
 else
   if [[ $1 == "package" ]]; then
     COMMAND=package
+  elif [[ $1 == "install" ]]; then
+    COMMAND=install
+  elif [[ $1 == "exec" ]]; then
+    EMACSLOADPATH=$($EMACS -Q --batch --eval '(message (mapconcat (quote identity) (append (file-expand-wildcards "elpa/*" t) load-path) ":"))' 2>&1) ${@:2}
   else
-    if [[ $1 == "install" ]]; then
-      COMMAND=install
-    else
-      if [[ $1 == "exec" ]]; then
-        EMACSLOADPATH=$($EMACS -Q --batch --eval '(message (mapconcat (quote identity) (append (file-expand-wildcards "elpa/*" t) load-path) ":"))' 2>&1) ${@:2}
-      else
-        echo "Could not find task '$1'."
-        echo "usage: carton [INSTALL]"
-        echo "       carton package"
-        echo "       carton exec [COMMAND]"
-         
-        exit 1
-      fi
-    fi
+    echo "Could not find task '$1'."
+    echo "usage: carton [INSTALL]"
+    echo "       carton package"
+    echo "       carton exec [COMMAND]"
+
+    exit 1
   fi
 fi
 
