Add `carton exec` command.

diff --git a/bin/carton b/bin/carton
--- a/bin/carton
+++ b/bin/carton
@@ -15,13 +15,19 @@ else
     if [[ $1 == "install" ]]; then
       COMMAND=install
     else
-      echo "Could not find task '$1'."
-      echo "usage: carton [install]"
-      echo "       carton package"
-
-      exit 1
+      if [[ $1 == "exec" ]]; then
+        EMACSLOADPATH=$(emacs -Q --batch --eval '(message (mapconcat (quote identity) (append (file-expand-wildcards "elpa/*" t) load-path) ":"))' 2>&1) ${@:2}
+      else
+        echo "Could not find task '$1'."
+        echo "usage: carton [install]"
+        echo "       carton package"
+         
+        exit 1
+      fi
     fi
   fi
 fi
 
-EMACS --batch --load $CARTON_EL -Q --eval "(progn (carton-setup \"${PWD}\") (carton-${COMMAND}))"
+if [[ -n $COMMAND ]]; then
+  EMACS --batch --load $CARTON_EL --eval "(progn (carton-setup \"${PWD}\") (carton-${COMMAND}))"
+fi
